### PR TITLE
Allow setting of minimum clearance from left and/or right edge...

### PR DESCRIPTION
**Pull request by dougkeen**
…required to enable swipe gestures. Addresses issue 45 (on upstream).

### CODE REVIEW

**Comment by Cederman** [comment]
There seems to be merge conflicts. Can you fix them?

**Comment by dougkeen** [comment]
I can't now, but maybe I'll have some time over the next few days.

**Comment by svenjens** [comment]
Any update on this?

**Comment by dougkeen** [comment]
Should be ready to go now

**Comment by Cederman** [comment]
Awesome. Merging 💪

**Comment by svenjens** [comment]
Will you also do a new release?

**Pull request merged**
